[database]
#Golbat Database settings
username = "user"
password = "password"
host = "127.0.0.1"
port = "3306"
name = "golbatdbname"

[discord]
#Discord bot token
token = ""
#channel IDs for Discord that you want the boards posted to, array support infinite channels
channelIDs = ["yourchannelid","moarchannelids"]

[level_emoji]
"1" = "1️⃣"
"3" = "3️⃣"
"4" = "4️⃣"
"5" = "5️⃣"
"6" = "📣"
"9" = "🐲"
"11" = "⚫"
"13" = "⚫"

[reward_emoji]
"2" = "🛒"
"3" = "🌟"
"7" = "😈"
"12" = "⚡️"

[lure_emoji]
"501" = "🎣"
"502" = "❄️"
"503" = "🌿"
"504" = "🧲"
"505" = "💧"
"506" = "🏅"

[rocket_emoji]
"1" = "🥉"
"2" = "🥈"
"3" = "🥇"

[event_emoji]
"8" = "🟢"
"9" = "🏆"

[api]
#golbat url and port
url = "http://127.0.0.1:9001"
#golbat secret leave blank if not used
secret = ""

#coordinates below define the area in which API calls are made - adjust if needed for multi-instances where you only want to show active counts for a certain area, defaults cover the world
[coordinates.min]
latitude = -90
longitude = -180

[coordinates.max]
latitude = 90
longitude = 180

[config]
#refresh time in seconds that the board will query the db
refreshInterval = 60
errorRefreshInterval = 30
#if set to false active counts will be removed from hundos/nundos and API calls won't be made
includeActiveCounts = true 
#Title of the embed
EmbedTitle = "Today's Pokémon Stats"
#Delete old embeds before sending a new.
DeleteOldEmbeds = true